<?php
/**
 * @file
 * Code for the Ombuslide feature.
 */

include_once('ombugallery.features.inc');


/**
 * Implements hook_bean_types_api_info().
 */
function ombugallery_bean_types_api_info() {
  return array(
    'api' => bean_current_version(),
  );
}

/**
 * Implements hook_bean_types().
 */
function ombugallery_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'ombugallery');

  $plugins['ombugallery'] = array(
    'name' => 'ombugallery',
    'label' => t('Slideshow'),
    'handler' => array(
      'class' => 'OmbuslideBean',
      'parent' => 'BeanPlugin',
      'path' => $plugin_path . '/includes',
      'file' => 'OmbuslideBean.php',
    ),
    'editable' => TRUE,
  );
  return $plugins;
}

/**
 * Implements hook_block_view_alter().
 */
function ombugallery_block_view_alter(&$data, $block) {
  // Add "add" link to block contextual links.
  if ($block->module == 'bean' && isset($data['content']) && is_array($data['content']) && array_key_exists('bean', $data['content'])) {
    foreach ($data['content']['bean'] as $id => $bean) {
      if (!empty($bean['#bundle']) && $bean['#bundle'] == 'ombugallery') {
        $field = field_info_field('field_slide');
        $path = field_collection_field_get_path($field);
        $data['content']['#contextual_links']['field_collection'] = array($path . '/add', array('bean', $id));
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ombugallery_form_bean_form_alter(&$form, $form_state) {
  // provide a simpler form for ordering and editing slides.
  if ($form['#bundle'] == 'ombugallery') {
    $path = drupal_get_path('module', 'ombugallery');
    drupal_add_js($path . '/ombugallery.admin.js');
    drupal_add_css($path . '/ombugallery.admin.css');
    $form['#submit'][] = 'ombugallery_form_bean_form_submit';
  }
}

/**
 * Submit callback for ombugallery form to redirect.
 */
function ombugallery_form_bean_form_submit($form, &$form_state) {
  if (isset($_GET['destination'])) {
    $destination = drupal_get_destination();
    $form_state['redirect'] = $destination['destination'];
  }
}

/**
 * Helper function to create a slide (which is a field_collection).
 */
function ombugallery_create_slide($bean, $image_path = NULL, $title = NULL, $description = NULL, $link = NULL) {

  $field_collection_item = entity_create('field_collection_item', array('field_name' => 'field_slide'));
  $field_collection_item->setHostEntity('bean', $bean);

  if ($image_path) {
    $directory = file_default_scheme() . '://slide';
    file_prepare_directory($directory, FILE_CREATE_DIRECTORY);
    $file = file_save_data(file_get_contents($image_path), $directory . '/slide.jpg');
    $field_collection_item->field_image[LANGUAGE_NONE][] = (array)$file;
  }
  if ($title ) {
    $field_collection_item->field_slide_title[LANGUAGE_NONE][]['value'] = $title;
  }
  if ($description) {
    $field_collection_item->field_slide_text[LANGUAGE_NONE][] = array(
      'value' => $description,
      'format' => 'default',
    );
  }
  if ($link) {
    $field_collection_item->field_link[LANGUAGE_NONE][] = $link;
  }
  $field_collection_item->save();

  return $field_collection_item;
}
