<?php
/**
 * @file
 * Code for the Ombuslide feature.
 */

include_once('ombuslide.features.inc');


/**
 * Implements hook_bean_types_api_info().
 */
function ombuslide_bean_types_api_info() {
  return array(
    'api' => bean_current_version(),
  );
}

/**
 * Implements hook_bean_types().
 */
function ombuslide_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'ombuslide');

  $plugins['ombuslide'] = array(
    'name' => 'ombuslide',
    'label' => t('Slideshow'),
    'handler' => array(
      'class' => 'OmbuslideBean',
      'parent' => 'BeanPlugin',
      'path' => $plugin_path . '/includes',
      'file' => 'OmbuslideBean.php',
    ),
    'editable' => TRUE,
  );
  return $plugins;
}

/**
 * Implements hook_theme()
 */
function ombuslide_theme($existing, $type, $theme, $path) {
  return array(
    'ombuslide_default' => array(
      'variables' => array(
        'items' => NULL,
        'type' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_block_view_alter().
 */
function ombuslide_block_view_alter(&$data, $block) {
  // Add "add" link to block contextual links.
  if ($block->module == 'bean' && isset($data['content']) && is_array($data['content']) && array_key_exists('bean', $data['content'])) {
    foreach ($data['content']['bean'] as $id => $bean) {
      if (!empty($bean['#bundle']) && $bean['#bundle'] == 'ombuslide') {
        $field = field_info_field('field_slide');
        $path = field_collection_field_get_path($field);
        $data['content']['#contextual_links']['field_collection'] = array($path . '/add', array('bean', $id));
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ombuslide_form_bean_form_alter(&$form, $form_state) {
  // provide a simpler form for ordering and editing slides.
  if ($form['#bundle'] == 'ombuslide') {
    $path = drupal_get_path('module', 'ombuslide');
    drupal_add_js($path . '/ombuslide.admin.js');
    drupal_add_css($path . '/ombuslide.admin.css');
    $form['#submit'][] = 'ombuslide_form_bean_form_submit';
  }
}

/**
 * Implements hook_bean_styles().
 */
function ombuslide_bean_styles() {
  return array(
    'slideshow' => array(
      'label'          => 'Slideshow',
      'class'          => 'SlideshowBeanStyle',
      'bean_types'     => array(
        'ombuslide',
      ),
    )
  );
}

/**
 * Implements hook_bean_style_options_alter().
 */
function ombuslide_bean_style_options_alter(&$options, $context) {
  // Remove default option for slideshows, since we always want a slideshow
  // style displayed.
  if ($context['bundle'] == 'ombuslide') {
    unset($options['']);
  }
}

/**
 * Submit callback for ombuslide form to redirect.
 */
function ombuslide_form_bean_form_submit($form, &$form_state) {
  if (isset($_GET['destination'])) {
    $destination = drupal_get_destination();
    $form_state['redirect'] = $destination['destination'];
  }
}

/**
 * Theme callback.
 *
 * Themes a field collection as a ombuslide.
 */
function theme_ombuslide_default($variables) {
  $items     = $variables['items'];

  $output = '';

  if (!$items) {
    return $output;
  }

  $items = array();
  foreach ($variables['items'] as $item) {
    $item['data'] = drupal_render($item['data']);
    $items[] = $item;
  }

  $output .= theme('item_list', array('items' => $items, 'attributes' => array('class' => array('slides'))));

  $classes = 'ombuslide ombuslide-slideshow ombuslide-' . $variables['type'];

  // Add unique id.
  $id = drupal_html_id('ombuslide');
  $output = '<div id="' . $id . '" class="' . $classes . '">' . $output . '</div><div class="clearfix"></div>';

  // Add js.
  $path = drupal_get_path('module', 'ombuslide') . '/styles/default';
  drupal_add_js($path . '/js/jquery.cycle.all.js');
  drupal_add_js($path . '/js/ombuslide.js');
  drupal_add_js(array('ombuslide' => array($id => array())), 'setting');

  // Default values. These are overriden by those from the formatter settings
  // form.
  $opts = array(
    'timeout' => 0,
    'next' => '#ombuslide .next',
    'prev' => '#ombuslide .prev',
    'width' => 'auto',
    'height' => 'auto',
    'speed' => '300',
  );

  drupal_add_js(array('ombuslide' => array($id => $opts)), 'setting');
  drupal_add_css($path . '/css/ombuslide.default.css');

  return $output;
}

/**
 * Helper function to create a slide (which is a field_collection).
 */
function ombuslide_create_slide($bean, $image_path = NULL, $title = NULL, $description = NULL, $link = NULL) {

  $field_collection_item = entity_create('field_collection_item', array('field_name' => 'field_slide'));
  $field_collection_item->setHostEntity('bean', $bean);

  if ($image_path) {
    $directory = file_default_scheme() . '://slide';
    file_prepare_directory($directory, FILE_CREATE_DIRECTORY);
    $file = file_save_data(file_get_contents($image_path), $directory . '/slide.jpg');
    $field_collection_item->field_image[LANGUAGE_NONE][] = (array)$file;
  }
  if ($title ) {
    $field_collection_item->field_slide_title[LANGUAGE_NONE][]['value'] = $title;
  }
  if ($description) {
    $field_collection_item->field_slide_text[LANGUAGE_NONE][] = array(
      'value' => $description,
      'format' => 'default',
    );
  }
  if ($link) {
    $field_collection_item->field_link[LANGUAGE_NONE][] = $link;
  }
  $field_collection_item->save();

  return $field_collection_item;
}
